#!/bin/bash

if [[ "$1" = "" || "$2" = "" ]] ; then
	echo "Usage: z-build <gplay|fdroid> <debug|release> [install]"
	exit
fi

VERSION_NAME=`cat gradle.properties | grep VERSION_NAME | sed -e 's/^[ ]*VERSION_NAME[ ]*=//' | sed -e 's/[ ]*$//'`

if [[ "$3" = "install" ]] ; then
	PREFIX="install"
else
	PREFIX="assemble"
fi

case "$2" in
	debug)
		SUFFIX="Debug"
		;;

	release)
		SUFFIX="Release"
		;;

	*)
		echo "Unknown build type: $2"
		exit
esac

case "$1" in
	gplay)
		TASK="ForgplayWithgplayWithzeemoteWoutko"
		LCTASK="forgplaywithgplaywithzeemotewoutko"
		SRCNAME="gloomy-dungeons-2-forgplay-withgplay-withzeemote-woutko-release.apk"
		DSTNAMEPART="gloomy-dungeons-2-fullnfree-${VERSION_NAME}"
		;;

	fdroid)
		TASK="ForfdroidWoutgplayWoutzeemoteWoutko"
		LCTASK="forfdroidwoutgplaywoutzeemotewoutko"
		;;

	*)
		echo "Unknown build variant: $1"
		exit
esac

./gradlew "${PREFIX}${TASK}${SUFFIX}"

if [[ "$2" = "release" && -e "temp" && "$SRCNAME" != "" && "$DSTNAMEPART" != "" ]] ; then
	[ -e "temp/${DSTNAMEPART}.apk" ] && rm "temp/${DSTNAMEPART}.apk"
	[ -e "temp/${DSTNAMEPART}.txt" ] && rm "temp/${DSTNAMEPART}.txt"
	[ -e "build/outputs/apk/${SRCNAME}" ] && cp "build/outputs/apk/${SRCNAME}" "temp/${DSTNAMEPART}.apk"
	[ -e "build/outputs/proguard/${LCTASK}/release/mapping.txt" ] && cp "build/outputs/proguard/${LCTASK}/release/mapping.txt" "temp/${DSTNAMEPART}.txt"
fi
