#!/bin/bash

if [[ "$1" = "" || "$2" = "" ]] ; then
	echo "Usage: z-build <gplay|gplayhalloween|fdroid> <debug|release> [install]"
	exit
fi

VERSION_NAME=`cat gradle.properties | grep VERSION_NAME | sed -e 's/^[ ]*VERSION_NAME[ ]*=//' | sed -e 's/[ ]*$//'`

if [[ "$3" = "install" ]] ; then
	PREFIX="install"
else
	PREFIX="assemble"
fi

case "$2" in
	debug)
		SUFFIX="Debug"
		;;

	release)
		SUFFIX="Release"
		;;

	*)
		echo "Unknown build type: $2"
		exit
esac

case "$1" in
	gplay)
		TASK="ForgplayWithgplayWithzeemoteWoutkoWouthalloween"
		LCTASK="forgplaywithgplaywithzeemotewoutkowouthalloween"
		SRCNAME="gloomy-dungeons-2-forgplay-withgplay-withzeemote-woutko-wouthalloween-release.apk"
		DSTNAMEPART="gloomy-dungeons-2-fullnfree-${VERSION_NAME}"
		;;

	gplayhalloween)
		TASK="ForgplayhalloweenWithgplayWithzeemoteWoutkoWithhalloween"
		LCTASK="forgplayhalloweenwithgplaywithzeemotewoutkowithhalloween"
		SRCNAME="gloomy-dungeons-2-forgplayhalloween-withgplay-withzeemote-woutko-withhalloween-release.apk"
		DSTNAMEPART="gloomy-dungeons-2-halloween-${VERSION_NAME}"
		;;

	fdroid)
		TASK="ForfdroidWoutgplayWoutzeemoteWoutkoWouthalloween"
		LCTASK="forfdroidwoutgplaywoutzeemotewoutkowouthalloween"
		;;

	*)
		echo "Unknown build variant: $1"
		exit
esac

./gradlew "${PREFIX}${TASK}${SUFFIX}"

if [[ "$2" = "release" && -e "temp" && "$SRCNAME" != "" && "$DSTNAMEPART" != "" ]] ; then
	[ -e "temp/${DSTNAMEPART}.apk" ] && rm "temp/${DSTNAMEPART}.apk"
	[ -e "temp/${DSTNAMEPART}.txt" ] && rm "temp/${DSTNAMEPART}.txt"
	[ -e "build/outputs/apk/${SRCNAME}" ] && cp "build/outputs/apk/${SRCNAME}" "temp/${DSTNAMEPART}.apk"
	[ -e "build/outputs/mapping/${LCTASK}/release/mapping.txt" ] && cp "build/outputs/mapping/${LCTASK}/release/mapping.txt" "temp/${DSTNAMEPART}.txt"
fi
