<?php

defined('POPLR') or die();

return array(
	'achievements.title.0' => 'Руки в крови',
	'achievements.description.0' => 'Убить 5 монстров',
	'achievements.title.5' => 'Освоил двери',
	'achievements.description.5' => 'Открыть 5 дверей',
	'achievements.title.10' => 'Освоил секреты',
	'achievements.description.10' => 'Найти 5 секретов',
	'achievements.title.15' => 'Всех убью, один останусь',
	'achievements.description.15' => '100% убийств 5 уровней подряд',
	'achievements.title.16' => 'Коллекционер',
	'achievements.description.16' => '100% вещей 5 уровней подряд',
	'achievements.title.17' => 'Железная Воля',
	'achievements.description.17' => '100% секретов 5 уровней подряд',
	'achievements.title.1' => 'Начинающий мясник',
	'achievements.description.1' => 'Убить 25 монстров',
	'achievements.title.6' => 'Хранитель дверей',
	'achievements.description.6' => 'Открыть 25 дверей',
	'achievements.title.11' => 'Исследователь',
	'achievements.description.11' => 'Найти 10 секретов',
	'achievements.title.18' => 'Опустошитель',
	'achievements.description.18' => '100% убийств 10 уровней подряд',
	'achievements.title.19' => 'Плюшкин',
	'achievements.description.19' => '100% вещей 10 уровней подряд',
	'achievements.title.20' => 'Сверх-ниндзя',
	'achievements.description.20' => '100% секретов 10 уровней подряд',
	'achievements.title.2' => 'Это моя работа',
	'achievements.description.2' => 'Убить 100 монстров',
	'achievements.title.7' => 'Отмычка – мой друг',
	'achievements.description.7' => 'Открыть 100 дверей',
	'achievements.title.12' => 'Следуй за белым кроликом',
	'achievements.description.12' => 'Найти 25 секретов',
	'achievements.title.3' => 'Рон Джэмбо',
	'achievements.description.3' => 'Убить 500 монстров',
	'achievements.title.8' => 'Синий ключ, зеленый ключ, какая разница',
	'achievements.description.8' => 'Открыть 500 дверей',
	'achievements.title.13' => 'Меня зовут Человек-рентген',
	'achievements.description.13' => 'Найти 50 секретов',
	'achievements.title.4' => 'Я вижу мертвых монстров. Много',
	'achievements.description.4' => 'Убить 1000 монстров',
	'achievements.title.9' => 'Твоя принцесса в другом замке',
	'achievements.description.9' => 'Открыть 1000 дверей',
	'achievements.title.14' => 'Индиана Форд',
	'achievements.description.14' => 'Найти 100 секретов',
	'achievements.title.21' => 'Шустрик',
	'achievements.description.21' => 'Пройти обучение и первый эпизод меньше чем за 4:30',
);
