<?php

defined('POPLR') or die();

return array(
	'achievements.title.0' => 'Hands in blood',
	'achievements.description.0' => 'Kill 5 monsters',
	'achievements.title.5' => 'Doors mastered',
	'achievements.description.5' => 'Open 5 doors',
	'achievements.title.10' => 'Secrets mastered',
	'achievements.description.10' => 'Find 5 secrets',
	'achievements.title.15' => 'No country for old monsters',
	'achievements.description.15' => '100% kills in 5 levels in a row',
	'achievements.title.16' => 'Collector',
	'achievements.description.16' => '100% items in 5 levels in a row',
	'achievements.title.17' => 'Iron Will',
	'achievements.description.17' => '100% secrets in 5 levels in a row',
	'achievements.title.1' => 'Apprentice butcher',
	'achievements.description.1' => 'Kill 25 monsters',
	'achievements.title.6' => 'Doorkeeper',
	'achievements.description.6' => 'Open 25 doors',
	'achievements.title.11' => 'The Explorer',
	'achievements.description.11' => 'Find 10 secrets',
	'achievements.title.18' => 'Devastator',
	'achievements.description.18' => '100% kills in 10 levels in a row',
	'achievements.title.19' => 'Loota',
	'achievements.description.19' => '100% items in 10 levels in a row',
	'achievements.title.20' => 'Ultimate ninja',
	'achievements.description.20' => '100% secrets in 10 levels in a row',
	'achievements.title.2' => 'It’s my job',
	'achievements.description.2' => 'Kill 100 monsters',
	'achievements.title.7' => 'Picklock is my friend',
	'achievements.description.7' => 'Open 100 doors',
	'achievements.title.12' => 'Follow the white rabbit',
	'achievements.description.12' => 'Find 25 secrets',
	'achievements.title.3' => 'Ron Jambo',
	'achievements.description.3' => 'Kill 500 monsters',
	'achievements.title.8' => 'Blue key, green key, what’s the difference',
	'achievements.description.8' => 'Open 500 doors',
	'achievements.title.13' => 'My name is RentgenMan',
	'achievements.description.13' => 'Find 50 secrets',
	'achievements.title.4' => 'I see dead monsters. A lot',
	'achievements.description.4' => 'Kill 1000 monsters',
	'achievements.title.9' => 'Your princess is in another castle',
	'achievements.description.9' => 'Open 1000 doors',
	'achievements.title.14' => 'Indiana Ford',
	'achievements.description.14' => 'Find 100 secrets',
	'achievements.title.21' => 'Quicky',
	'achievements.description.21' => 'Complete tutorial and first episode in less then 4:30',
);
